### ISSUE TITLE
[PE-D][Tester C] format of delete_asgn  different from actual

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-4/tp#154]
![image.png](https://raw.githubusercontent.com/Wong-Jia-Jun/ped/main/files/e0e9c797-1b85-4b68-baed-29f4e2ba5159.png)

description : format given is delete but when executing delete gets unknown error

steps: delete n/Lab1 `enter`

expected: Assignment: Lab1 Deleted

actual : Unknown command

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Wong-Jia-Jun/ped#2

**Comment by chunzkok** [comment]
duplicate
