### ISSUE TITLE
[PE-D][Tester B] UG: delete assignment example input error, when deleting an assignment, assignment name has an underscore

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-4/tp#173]
if we follow ug’s way of deleting assignment an error is thrown because of the underscore in the name of the assignment. This should be rectified since readers will follow the UG closely when trying out the product.

![ug assignemnt error 2.png](https://raw.githubusercontent.com/FredericChow00/ped/master/files/7e0ed7a3-ebb8-438a-b6ad-c1026ba87bd6.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: FredericChow00/ped#4

**Comment by TamKengHong** [comment]
duplicate
