### ISSUE TITLE
NullPointerException when assignmentName is not in map

### ISSUE THREAD

**Issue by WilliamHaiweiGu** [AY2223S2-CS2103T-T14-4/tp#202]
During the application starting phase, if the assignment name is not already in `AssigmentList.assignmentMap`, `AssignmentList.java:137` will set `toAdd` to `null` and throw `NullPointerException`.
When this happens, the GUI don't even get to be displayed and the application crashes.

How to reproduce (in codebase):

1. Delete `data` folder
2. Open application
3. Execute `clear`
4. Import [0.csv](https://github.com/AY2223S2-CS2103T-T14-4/tp/files/11147704/0.csv)
5. Close application
6. Re-open application

Observed result: `NullPointerException` is thrown, no GUI displayed.

**Comment by TamKengHong** [comment]
![image](https://user-images.githubusercontent.com/59087730/229805054-a5027004-48bc-4171-bab1-213aff9b30e3.png)

I think this is a problem with the data
It is specified that every student will have the a submission for every existing assignment

Nevertheless I will still put an error message if that is the case:
![image](https://user-images.githubusercontent.com/59087730/229820373-e5339b42-77a9-4a83-9438-4de611c866b0.png)

This will not start the GUI as the error happens within the initialization stage

Maybe we can put some specifications in the user guide
