### ISSUE TITLE
Bug: assignment list data is not kept across sessions

### ISSUE THREAD

**Issue by WilliamHaiweiGu** [AY2223S2-CS2103T-T14-4/tp#215]
How to reproduce:
1. Open application.
2. Execute `clear`
3. Execute `add_asgn n/x`
4. Execute `list_asgn`. Observe that assignment x is added
5. Close and reopen application.
6. Execute `list_asgn`. Observe that no more assignments exist!

**Comment by TamKengHong** [comment]
intended :)

**Comment by WilliamHaiweiGu** [comment]
Resolved: works as intended

**Comment by TamKengHong** [comment]
will add a check to make sure assignments can only be created if there are students

**Comment by WilliamHaiweiGu** [comment]
Resolved: Fixed via #219
